In [4]:
import pandas as pd
import numpy as np
import random
import io

In [5]:
# Read the database
# En esta base podrás encontrar información sobre los hoteles, mercados y museos que se 
# encuentran en el Centro Histórico de la Ciudad de México.

data = pd.read_csv("econdata.csv")
data

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
1,1,"19.4346139576,-99.1413808393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_008_01,Cuautémoc,A,Museo,Museo Nacional de Arquitectura Palacio de Bell...
2,2,"19.4340695945,-99.1306348409","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuautémoc,A,Museo,Santa Teresa
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
4,4,"19.42358238,-99.12451093","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_115_12,Venustiano Carranza,B,Hotel,real
...,...,...,...,...,...,...,...,...
225,225,"19.43094655,-99.12455418","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_027_04,Venustiano Carranza,B,Hotel,Gran Veracruz
226,226,"19.4416748524,-99.1365878489","{""type"": ""Polygon"", ""coordinates"": [[[-99.1370...",004_052_01,Cuauhtémoc,B,Mercado,De Muebles
227,227,"19.4307201342,-99.1491381087","{""type"": ""Polygon"", ""coordinates"": [[[-99.1498...",002_052_02,Cuauhtémoc,B,Mercado,Artesanías Ciudadela
228,228,"19.4406567734,-99.1394531646","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_069_01,Cuautémoc,B,Museo,Tequila y Mescal
229,229,"19.4346765421,-99.1318394918","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",005_145_14,Cuautémoc,A,Museo,Templo Mayor

## Funciones de muestreo

# 1. Muestreo aleatorio simple:

In [6]:
#importar los registrs de forma aleatoria

aleat_8 = data.sample(n=8)
aleat_8

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
173,173,"19.4314834886,-99.1259717478","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",006_026_38,Cuautémoc,A,Hotel,Soledad
13,13,"19.43878785,-99.1490443182","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_147_02,Cuautémoc,B,Hotel,Monaco
59,59,"19.4275850427,-99.1397624613","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_061_03,Cuautémoc,A,Hotel,Señorial
124,124,"19.4297560476,-99.1253498219","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",006_052_01,Cuautémoc,A,Hotel,Universo
35,35,"19.43811894,-99.13770698","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_087_01,Cuautémoc,A,Hotel,La Marina
197,197,"19.4399151122,-99.149385962","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_153_01,Cuautémoc,B,Hotel,Mina
104,104,"19.43397933,-99.13044075","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuautémoc,A,Hotel,Palacio
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria

In [7]:
#Eligiendo proporcion
prop_25 = data.sample(frac = 0.25)
prop_25.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
222,222,"19.4397905042,-99.134628735","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_063_10,Cuautémoc,A,Hotel,Ladero
153,153,"19.4241764183,-99.1254198454","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_133_29,Venustiano Carranza,B,Hotel,Navio
199,199,"19.4330530554,-99.1343604057","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_024_01,Cuautémoc,A,Hotel,Majestic
142,142,"19.4263681354,-99.1327278126","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_127_14,Cuautémoc,A,Hotel,Ambar
191,191,"19.43985567,-99.14782916","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_079_12,Cuautémoc,B,Hotel,Ferrol

## Muestreo sistemático

In [8]:
def systematic_sampling(data, step):
    indexes = np.arange(0, len(data), step = step)
    systematic_sample = data.iloc[indexes] #seleccionar datos basados en su posición entera (índice numérico)
    return systematic_sample


systematic_sample = systematic_sampling(data,3)
systematic_sample

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauhtémoc,B,Mercado,Pino Suárez
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
6,6,"19.43553422,-99.12324801","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",318_116_11,Venustiano Carranza,B,Hotel,San Antonio Tomatlan
9,9,"19.4407152937,-99.1498060057","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_146_22,Cuautémoc,B,Hotel,Detroit
12,12,"19.43990186,-99.14813347","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_079_16,Cuautémoc,B,Hotel,La Paz
...,...,...,...,...,...,...,...,...
216,216,"19.4247697438,-99.1249707246","{""type"": ""Polygon"", ""coordinates"": [[[-99.1250...",323_118_37,Venustiano Carranza,B,Mercado,Lamininas de La Merced
219,219,"19.4234096295,-99.1438351156","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_118_03,Cuautémoc,B,Hotel,Prado Floresta
222,222,"19.4397905042,-99.134628735","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_063_10,Cuautémoc,A,Hotel,Ladero
225,225,"19.43094655,-99.12455418","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_027_04,Venustiano Carranza,B,Hotel,Gran Veracruz
228,228,"19.4406567734,-99.1394531646","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_069_01,Cuautémoc,B,Museo,Tequila y Mescal

## Muestreo Estratificado

In [9]:
data["estratificado"] = data["delegacion"] + "," + data["tipo"]
(data["estratificado"].value_counts()/len(data)).sort_values(ascending = False)

estratificado
Cuautémoc,Hotel                0.643478
Cuautémoc,Museo                0.156522
Venustiano Carranza,Hotel      0.078261
Cuauhtémoc,Mercado             0.073913
Venustiano Carranza,Mercado    0.047826
Name: count, dtype: float64

Nuestros datos dicen que la proporcion es la siguiente:
1. Hoteles Cuauhtemoc: 0,5
2. Museos en "" : 0.2
3. Hoteles en Venustiano Carranza: 0.1
4. Mercados en Cuauhtemoc: 0.1
5. Mercados en Venusiano Carranza: 0.1

In [14]:
import pandas as pd

def data_estratificada(df, strat, proporciones, random_state=None):
    # DataFrame resultante
    df_estratificado = pd.DataFrame(columns=df.columns)
    
    # Iterar sobre cada estrato
    for valor_strat in strat:
        # Filtrar por el valor del estrato
        df_filtrado = df[df['estratificado'] == valor_strat]
        
        # Definir el tamaño de la muestra
        num_samples = int(proporciones[valor_strat] * len(df))
        if len(df_filtrado) < num_samples:
            num_samples = len(df_filtrado)
        
        # Extraer la muestra
        df_sample = df_filtrado.sample(n=num_samples, random_state=random_state)
        
        # Concatenar el resultado
        df_estratificado = pd.concat([df_estratificado, df_sample], ignore_index=True)
    
    return df_estratificado

In [15]:
# Definición de los valores y proporciones
valores_strat = [
    "Cuauhtemoc,hotel", 
    "Cuauhtemoc,museo", 
    "Venustiano Carranza,hotel", 
    "Cuauhtemoc,mercado", 
    "Venustiano Carranza,mercado"
]

proporciones = {
    "Cuauhtemoc,hotel": 0.5,
    "Cuauhtemoc,museo": 0.2,
    "Venustiano Carranza,hotel": 0.1,
    "Cuauhtemoc,mercado": 0.1,
    "Venustiano Carranza,mercado": 0.1
}

# Generación de la muestra
muestra_estratificada = data_estratificada(data, valores_strat, proporciones, random_state=42)